server:
  port: ${PORT:2002}

spring:
  application:
    name: inventory-management-api-spring

app:
  cors-origin: ${CORS_ORIGIN:*}
  master-email: ${MASTER_EMAIL:devhshoon@gmail.com}
  firebase:
    app-env: ${APP_ENV:development}
    service-account-path-dev: ${FIREBASE_SERVICE_ACCOUNT_PATH_DEV:secret/firebase.dev.json}
    service-account-path-prod: ${FIREBASE_SERVICE_ACCOUNT_PATH_PROD:secret/firebase.prod.json}
    project-id-dev: ${FIREBASE_PROJECT_ID_DEV:}
    client-email-dev: ${FIREBASE_CLIENT_EMAIL_DEV:}
    private-key-dev: ${FIREBASE_PRIVATE_KEY_DEV:}
    project-id-prod: ${FIREBASE_PROJECT_ID_PROD:}
    client-email-prod: ${FIREBASE_CLIENT_EMAIL_PROD:}
    private-key-prod: ${FIREBASE_PRIVATE_KEY_PROD:}
